config/routes.rb
PhoneSales::Application.routes.draw do

  devise_for :users
  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get "pages/about"
  get "pages/contact"
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  root 'listings#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :address, :city, :state, presence: true

  belongs_to :listing
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :seller]

  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
    # On the sales page, show all orders where the current user is the seller.
    # Display when they were created so the most recent order is first
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
    # On the purchases page, show all purchases where the current user is the buyer.
    # Display when they were created so the most recent purchase is first
  end

  # # GET /orders
  # # GET /orders.json
  # def index
  #   @orders = Order.all
  # end

  # GET /orders/1
  # GET /orders/1.json
  # def show
  # end

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
    # Find the id of the listing you want to buy in the url
  end

  # GET /orders/1/edit
  # def edit
  # end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user
    # The seller is the same as the user who created the listing

    @order.listing_id = @listing.id
    # Find the id of the listing you want to buy in the url
    @order.buyer_id = current_user.id
    # When you create the order
    # Fill in the buyer_id column with the current_user.id
    @order.seller_id = @seller.id

    Stripe.api_key = ENV["STRIPE_API_KEY"]
    # Tell Stripe the secret key
    token = params[:stripeToken]
    # Looks in form data. Pulls out stripeToken and save it in var called token

    begin
      # Creates a new Stripe charge. Located on stripe website. Charges/create a new change in docs
      charge = Stripe::Charge.create(
        :amount => (@listing.price * 100).floor,
        # Set the amount to the listing price and convert into cents. Floor makes it an integer not a decimal
        :currency => "usd",
        :card => token
        # Card number is in the token
        )
        flash[:notice] = "Thanks for ordering!"
    rescue Stripe::CardError => e
      # If error, show error message. Like if the card was declined
      flash[:danger] = e.message
    end

    # Transfer money to receipient
    transfer = Stripe::Transfer.create(
      :amount => (@listing.price * 95).floor,
      # 95 percent to seller. 5 for me. price converted to cents
      :currency => "usd",
      :recipient => @seller.recipient
    )

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  # def update
  #   respond_to do |format|
  #     if @order.update(order_params)
  #       format.html { redirect_to @order, notice: 'Order was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: 'edit' }
  #       format.json { render json: @order.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /orders/1
  # DELETE /orders/1.json
  # def destroy
  #   @order.destroy
  #   respond_to do |format|
  #     format.html { redirect_to orders_url }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag @listing.image.url %>
    </div>
    <h3><%= @listing.name %></h3>
    <h4><%= number_to_currency(@listing.price) %></h4>
  </div>
  <div class="col-md-8">

    <%= form_for([@listing, @order]) do |f| %>
      <% if @order.errors.any? %>
        <div id="error_explanation" class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

          <ul>
          <% @order.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div id="stripe_error" class="alert alert-danger" style="display:none">
        <noscript>Javascript is not enabled and is required for this form. First enable it in your web browser settings</noscript>
      </div>

      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :city %>
        <%= f.text_field :city, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :state %>
        <%= f.text_field :state, class: "form-control" %>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-md-8">
            <%= label :card_number, "Credit Card Number" %>
            <%= text_field_tag :card_number, nil, {:name => nil, :'data-stripe' => "number", class: "form-control" } %>
          </div>
          <div class="col-md-4">
            <%= label :card_code, "CVC" %>
            <%= text_field_tag :card_code, nil, {:name => nil, :'data-stripe' => "cvc", class: "form-control" } %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag nil, "Expiration Date" %>
        <div class="row">
          <div class="col-md-3">
            <%= select_month nil, { use_two_digit_numbers: true }, {:name => nil, :'data-stripe' => "exp-month", class: "form-control" } %>
          </div>
          <div class="col-md-3">
            <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+15 }, {:name => nil, :'data-stripe' => "exp-year", class: "form-control" } %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "Complete Order", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.address %></td>
        <td><%= order.city %></td>
        <td><%= order.state %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', listing_orders_path %>

app/views/orders/purchases.html.erb
<div class="center">
  <h2>Your Purchases History</h2>
</div>
    <table class="table table-striped table-bordered">
      <tr>
        <th class="center">Image</th>
        <th class="center">Item</th>
        <th class="center">Price</th>
        <th class="center">Seller</th>
        <th class="center">Date Purchased</th>

      </tr>

      <% @orders.each do |order| %>
        <tr>
          <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
          <td class="center"><%= order.listing.name %></td>
          <td class="center"><%= number_to_currency(order.listing.price) %></td>
          <td class="center"><%= order.seller.name %></td>
          <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
        </tr>
      <% end %>
    </table>


<br>
<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link", data: { no_turbolink: true } %>
<% end %>

app/views/orders/sales.html.erb
<div class="center">
  <h2>Your Sales History</h2>
</div>
    <table class="table table-striped table-bordered">
      <tr>
        <th class="center">Image</th>
        <th class="center">Item</th>
        <th class="center">Price</th>
        <th class="center">Customer</th>
        <th class="center">Date Sold</th>

      </tr>

      <% @orders.each do |order| %>
        <tr>
          <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
          <td class="center"><%= order.listing.name %></td>
          <td class="center"><%= number_to_currency(order.listing.price) %></td>
          <td class="center"><%= order.buyer.name %></td>
          <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
        </tr>
      <% end %>
    </table>


<br>
<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link", data: { no_turbolink: true } %>
<% end %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @order.state %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>